# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-16 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0015_release_0_10_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('bash', 'Bash'), ('c', 'C Language'), ('cpp', 'C++ Language'), ('java', 'Java Language'), ('scilab', 'Scilab')], max_length=24)),
                ('snippet', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='language',
        ),
        migrations.RemoveField(
            model_name='question',
            name='snippet',
        ),
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('bash', 'Bash'), ('c', 'C Language'), ('cpp', 'C++ Language'), ('java', 'Java Language'), ('scilab', 'Scilab')], max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='languageoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_options', to='yaksh.Question'),
        ),
    ]
