# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-01 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yaksh', '0016_auto_20191016_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'info'), ('warning', 'warning')], max_length=31)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.Course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.LearningModule')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
