# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-21 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0017_studentactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdiobasedtestcase',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
