FROM centos:7

MAINTAINER FOSSEE <pythonsupport@fossee.in>

RUN yum install git python3-pip mariadb-devel sudo java-1.8.0-openjdk java-1.8.0-openjdk-devel gcc python3-devel gcc-c++ -y

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk/

VOLUME /Sites/online_test

ADD Files/requirements-* /tmp/

RUN pip3 install -r /tmp/requirements-codeserver.txt && mkdir -p /Sites/online_test/yaksh_data/output /Sites/online_test/yaksh_data/data

WORKDIR /Sites/online_test

ADD Files/Start-codeserver.sh /Sites

EXPOSE 53579

CMD [ "/bin/bash" , "/Sites/Start-codeserver.sh" ]
